# CLEANING DATA
--> dropna & fillna

In [53]:
import pandas as pd
df = pd.read_csv("C:\\Users\\KIIT\\Desktop\\Padho Likho\\tips.csv").head(12)
print(df)

    total_bill   tip     sex smoker  day    time  size
0        16.99  1.01  Female     No  Sun  Dinner     2
1        10.34  1.66    Male     No  Sun  Dinner     3
2        21.01  3.50    Male     No  Sun  Dinner     3
3        23.68  3.31    Male     No  Sun  Dinner     2
4        24.59  3.61  Female     No  Sun  Dinner     4
5        25.29  4.71    Male     No  Sun  Dinner     4
6         8.77  2.00    Male     No  Sun  Dinner     2
7        26.88  3.12    Male     No  Sun  Dinner     4
8        15.04  1.96    Male     No  Sun  Dinner     2
9        14.78  3.23    Male     No  Sun  Dinner     2
10       10.27  1.71    Male     No  Sun  Dinner     2
11       35.26  5.00  Female     No  Sun  Dinner     4

In [21]:
df.dropna(axis=0)

    total_bill   tip     sex smoker  day    time  size
0        16.99  1.01  Female     No  Sun  Dinner     2
1        10.34  1.66    Male     No  Sun  Dinner     3
2        21.01  3.50    Male     No  Sun  Dinner     3
3        23.68  3.31    Male     No  Sun  Dinner     2
4        24.59  3.61  Female     No  Sun  Dinner     4
5        25.29  4.71    Male     No  Sun  Dinner     4
6         8.77  2.00    Male     No  Sun  Dinner     2
7        26.88  3.12    Male     No  Sun  Dinner     4
8        15.04  1.96    Male     No  Sun  Dinner     2
9        14.78  3.23    Male     No  Sun  Dinner     2
10       10.27  1.71    Male     No  Sun  Dinner     2
11       35.26  5.00  Female     No  Sun  Dinner     4

In [23]:
df.dropna(how="all")

    total_bill   tip     sex smoker  day    time  size
0        16.99  1.01  Female     No  Sun  Dinner     2
1        10.34  1.66    Male     No  Sun  Dinner     3
2        21.01  3.50    Male     No  Sun  Dinner     3
3        23.68  3.31    Male     No  Sun  Dinner     2
4        24.59  3.61  Female     No  Sun  Dinner     4
5        25.29  4.71    Male     No  Sun  Dinner     4
6         8.77  2.00    Male     No  Sun  Dinner     2
7        26.88  3.12    Male     No  Sun  Dinner     4
8        15.04  1.96    Male     No  Sun  Dinner     2
9        14.78  3.23    Male     No  Sun  Dinner     2
10       10.27  1.71    Male     No  Sun  Dinner     2
11       35.26  5.00  Female     No  Sun  Dinner     4

In [25]:
df.dropna(subset=["tip"])

    total_bill   tip     sex smoker  day    time  size
0        16.99  1.01  Female     No  Sun  Dinner     2
1        10.34  1.66    Male     No  Sun  Dinner     3
2        21.01  3.50    Male     No  Sun  Dinner     3
3        23.68  3.31    Male     No  Sun  Dinner     2
4        24.59  3.61  Female     No  Sun  Dinner     4
5        25.29  4.71    Male     No  Sun  Dinner     4
6         8.77  2.00    Male     No  Sun  Dinner     2
7        26.88  3.12    Male     No  Sun  Dinner     4
8        15.04  1.96    Male     No  Sun  Dinner     2
9        14.78  3.23    Male     No  Sun  Dinner     2
10       10.27  1.71    Male     No  Sun  Dinner     2
11       35.26  5.00  Female     No  Sun  Dinner     4

In [27]:
df.dropna(inplace=True)

In [29]:
df.dropna(thresh=1)

    total_bill   tip     sex smoker  day    time  size
0        16.99  1.01  Female     No  Sun  Dinner     2
1        10.34  1.66    Male     No  Sun  Dinner     3
2        21.01  3.50    Male     No  Sun  Dinner     3
3        23.68  3.31    Male     No  Sun  Dinner     2
4        24.59  3.61  Female     No  Sun  Dinner     4
5        25.29  4.71    Male     No  Sun  Dinner     4
6         8.77  2.00    Male     No  Sun  Dinner     2
7        26.88  3.12    Male     No  Sun  Dinner     4
8        15.04  1.96    Male     No  Sun  Dinner     2
9        14.78  3.23    Male     No  Sun  Dinner     2
10       10.27  1.71    Male     No  Sun  Dinner     2
11       35.26  5.00  Female     No  Sun  Dinner     4

In [35]:
df.fillna("Sh")

    total_bill   tip     sex smoker  day    time  size
0        16.99  1.01  Female     No  Sun  Dinner     2
1        10.34  1.66    Male     No  Sun  Dinner     3
2        21.01  3.50    Male     No  Sun  Dinner     3
3        23.68  3.31    Male     No  Sun  Dinner     2
4        24.59  3.61  Female     No  Sun  Dinner     4
5        25.29  4.71    Male     No  Sun  Dinner     4
6         8.77  2.00    Male     No  Sun  Dinner     2
7        26.88  3.12    Male     No  Sun  Dinner     4
8        15.04  1.96    Male     No  Sun  Dinner     2
9        14.78  3.23    Male     No  Sun  Dinner     2
10       10.27  1.71    Male     No  Sun  Dinner     2
11       35.26  5.00  Female     No  Sun  Dinner     4

In [37]:
df.fillna({"total_bill":"a","tip":"b","sex":"c" })

    total_bill   tip     sex smoker  day    time  size
0        16.99  1.01  Female     No  Sun  Dinner     2
1        10.34  1.66    Male     No  Sun  Dinner     3
2        21.01  3.50    Male     No  Sun  Dinner     3
3        23.68  3.31    Male     No  Sun  Dinner     2
4        24.59  3.61  Female     No  Sun  Dinner     4
5        25.29  4.71    Male     No  Sun  Dinner     4
6         8.77  2.00    Male     No  Sun  Dinner     2
7        26.88  3.12    Male     No  Sun  Dinner     4
8        15.04  1.96    Male     No  Sun  Dinner     2
9        14.78  3.23    Male     No  Sun  Dinner     2
10       10.27  1.71    Male     No  Sun  Dinner     2
11       35.26  5.00  Female     No  Sun  Dinner     4

In [39]:
df.fillna(method="ffill")

C:\Users\KIIT\AppData\Local\Temp\ipykernel_22672\3944122520.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill")

    total_bill   tip     sex smoker  day    time  size
0        16.99  1.01  Female     No  Sun  Dinner     2
1        10.34  1.66    Male     No  Sun  Dinner     3
2        21.01  3.50    Male     No  Sun  Dinner     3
3        23.68  3.31    Male     No  Sun  Dinner     2
4        24.59  3.61  Female     No  Sun  Dinner     4
5        25.29  4.71    Male     No  Sun  Dinner     4
6         8.77  2.00    Male     No  Sun  Dinner     2
7        26.88  3.12    Male     No  Sun  Dinner     4
8        15.04  1.96    Male     No  Sun  Dinner     2
9        14.78  3.23    Male     No  Sun  Dinner     2
10       10.27  1.71    Male     No  Sun  Dinner     2
11       35.26  5.00  Female     No  Sun  Dinner     4

In [41]:
df.fillna(method="ffill", axis=0)

C:\Users\KIIT\AppData\Local\Temp\ipykernel_22672\1271620647.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill", axis=0)

    total_bill   tip     sex smoker  day    time  size
0        16.99  1.01  Female     No  Sun  Dinner     2
1        10.34  1.66    Male     No  Sun  Dinner     3
2        21.01  3.50    Male     No  Sun  Dinner     3
3        23.68  3.31    Male     No  Sun  Dinner     2
4        24.59  3.61  Female     No  Sun  Dinner     4
5        25.29  4.71    Male     No  Sun  Dinner     4
6         8.77  2.00    Male     No  Sun  Dinner     2
7        26.88  3.12    Male     No  Sun  Dinner     4
8        15.04  1.96    Male     No  Sun  Dinner     2
9        14.78  3.23    Male     No  Sun  Dinner     2
10       10.27  1.71    Male     No  Sun  Dinner     2
11       35.26  5.00  Female     No  Sun  Dinner     4

In [45]:
df.fillna(12, inplace=True)
df

    total_bill   tip     sex smoker  day    time  size
0        16.99  1.01  Female     No  Sun  Dinner     2
1        10.34  1.66    Male     No  Sun  Dinner     3
2        21.01  3.50    Male     No  Sun  Dinner     3
3        23.68  3.31    Male     No  Sun  Dinner     2
4        24.59  3.61  Female     No  Sun  Dinner     4
5        25.29  4.71    Male     No  Sun  Dinner     4
6         8.77  2.00    Male     No  Sun  Dinner     2
7        26.88  3.12    Male     No  Sun  Dinner     4
8        15.04  1.96    Male     No  Sun  Dinner     2
9        14.78  3.23    Male     No  Sun  Dinner     2
10       10.27  1.71    Male     No  Sun  Dinner     2
11       35.26  5.00  Female     No  Sun  Dinner     4

In [47]:
df.fillna("python", limit=2)

    total_bill   tip     sex smoker  day    time  size
0        16.99  1.01  Female     No  Sun  Dinner     2
1        10.34  1.66    Male     No  Sun  Dinner     3
2        21.01  3.50    Male     No  Sun  Dinner     3
3        23.68  3.31    Male     No  Sun  Dinner     2
4        24.59  3.61  Female     No  Sun  Dinner     4
5        25.29  4.71    Male     No  Sun  Dinner     4
6         8.77  2.00    Male     No  Sun  Dinner     2
7        26.88  3.12    Male     No  Sun  Dinner     4
8        15.04  1.96    Male     No  Sun  Dinner     2
9        14.78  3.23    Male     No  Sun  Dinner     2
10       10.27  1.71    Male     No  Sun  Dinner     2
11       35.26  5.00  Female     No  Sun  Dinner     4

# REPLACE

In [49]:
df.replace(to_replace=1, value=22)

    total_bill   tip     sex smoker  day    time  size
0        16.99  1.01  Female     No  Sun  Dinner     2
1        10.34  1.66    Male     No  Sun  Dinner     3
2        21.01  3.50    Male     No  Sun  Dinner     3
3        23.68  3.31    Male     No  Sun  Dinner     2
4        24.59  3.61  Female     No  Sun  Dinner     4
5        25.29  4.71    Male     No  Sun  Dinner     4
6         8.77  2.00    Male     No  Sun  Dinner     2
7        26.88  3.12    Male     No  Sun  Dinner     4
8        15.04  1.96    Male     No  Sun  Dinner     2
9        14.78  3.23    Male     No  Sun  Dinner     2
10       10.27  1.71    Male     No  Sun  Dinner     2
11       35.26  5.00  Female     No  Sun  Dinner     4

In [51]:
df.replace([2,3], 33)

    total_bill    tip     sex smoker  day    time  size
0        16.99   1.01  Female     No  Sun  Dinner    33
1        10.34   1.66    Male     No  Sun  Dinner    33
2        21.01   3.50    Male     No  Sun  Dinner    33
3        23.68   3.31    Male     No  Sun  Dinner    33
4        24.59   3.61  Female     No  Sun  Dinner     4
5        25.29   4.71    Male     No  Sun  Dinner     4
6         8.77  33.00    Male     No  Sun  Dinner    33
7        26.88   3.12    Male     No  Sun  Dinner     4
8        15.04   1.96    Male     No  Sun  Dinner    33
9        14.78   3.23    Male     No  Sun  Dinner    33
10       10.27   1.71    Male     No  Sun  Dinner    33
11       35.26   5.00  Female     No  Sun  Dinner     4

In [53]:
df.replace("[A-Za-z]", "Rahul", regex=True)

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,RahulRahulRahulRahulRahulRahul,RahulRahul,RahulRahulRahul,RahulRahulRahulRahulRahulRahul,2
1,10.34,1.66,RahulRahulRahulRahul,RahulRahul,RahulRahulRahul,RahulRahulRahulRahulRahulRahul,3
2,21.01,3.50,RahulRahulRahulRahul,RahulRahul,RahulRahulRahul,RahulRahulRahulRahulRahulRahul,3
3,23.68,3.31,RahulRahulRahulRahul,RahulRahul,RahulRahulRahul,RahulRahulRahulRahulRahulRahul,2
4,24.59,3.61,RahulRahulRahulRahulRahulRahul,RahulRahul,RahulRahulRahul,RahulRahulRahulRahulRahulRahul,4
5,25.29,4.71,RahulRahulRahulRahul,RahulRahul,RahulRahulRahul,RahulRahulRahulRahulRahulRahul,4
6,8.77,2.00,RahulRahulRahulRahul,RahulRahul,RahulRahulRahul,RahulRahulRahulRahulRahulRahul,2
7,26.88,3.12,RahulRahulRahulRahul,RahulRahul,RahulRahulRahul,RahulRahulRahulRahulRahulRahul,4
8,15.04,1.96,RahulRahulRahulRahul,RahulRahul,RahulRahulRahul,RahulRahulRahulRahulRahulRahul,2
9,14.78,3.23,RahulRahulRahulRahul,RahulRahul,RahulRahulRahul,RahulRahulRahulRahulRahulRahul,2
10,10.27,1.71,RahulRahulRahulRahul,RahulRahul,RahulRahulRahul,RahulRahulRahulRahulRahulRahul,2
11,35.26,5.00,RahulRahulRahulRahulRahulRahul,RahulRahul,RahulRahulRahul,RahulRahulRahulRahulRahulRahul,4

In [59]:
df.replace({"tip":"[A-Z]"},22,regex=True)

    total_bill   tip     sex smoker  day    time  size
0        16.99  1.01  Female     No  Sun  Dinner     2
1        10.34  1.66    Male     No  Sun  Dinner     3
2        21.01  3.50    Male     No  Sun  Dinner     3
3        23.68  3.31    Male     No  Sun  Dinner     2
4        24.59  3.61  Female     No  Sun  Dinner     4
5        25.29  4.71    Male     No  Sun  Dinner     4
6         8.77  2.00    Male     No  Sun  Dinner     2
7        26.88  3.12    Male     No  Sun  Dinner     4
8        15.04  1.96    Male     No  Sun  Dinner     2
9        14.78  3.23    Male     No  Sun  Dinner     2
10       10.27  1.71    Male     No  Sun  Dinner     2
11       35.26  5.00  Female     No  Sun  Dinner     4

In [61]:
df.replace(1, method="ffill")

C:\Users\KIIT\AppData\Local\Temp\ipykernel_22672\2622724543.py:1: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  df.replace(1, method="ffill")

    total_bill   tip     sex smoker  day    time  size
0        16.99  1.01  Female     No  Sun  Dinner     2
1        10.34  1.66    Male     No  Sun  Dinner     3
2        21.01  3.50    Male     No  Sun  Dinner     3
3        23.68  3.31    Male     No  Sun  Dinner     2
4        24.59  3.61  Female     No  Sun  Dinner     4
5        25.29  4.71    Male     No  Sun  Dinner     4
6         8.77  2.00    Male     No  Sun  Dinner     2
7        26.88  3.12    Male     No  Sun  Dinner     4
8        15.04  1.96    Male     No  Sun  Dinner     2
9        14.78  3.23    Male     No  Sun  Dinner     2
10       10.27  1.71    Male     No  Sun  Dinner     2
11       35.26  5.00  Female     No  Sun  Dinner     4

In [63]:
df.replace(2,method="ffill", limit=6)

C:\Users\KIIT\AppData\Local\Temp\ipykernel_22672\1128759455.py:1: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  df.replace(2,method="ffill", limit=6)

    total_bill   tip     sex smoker  day    time  size
0        16.99  1.01  Female     No  Sun  Dinner     2
1        10.34  1.66    Male     No  Sun  Dinner     3
2        21.01  3.50    Male     No  Sun  Dinner     3
3        23.68  3.31    Male     No  Sun  Dinner     3
4        24.59  3.61  Female     No  Sun  Dinner     4
5        25.29  4.71    Male     No  Sun  Dinner     4
6         8.77  4.71    Male     No  Sun  Dinner     4
7        26.88  3.12    Male     No  Sun  Dinner     4
8        15.04  1.96    Male     No  Sun  Dinner     4
9        14.78  3.23    Male     No  Sun  Dinner     4
10       10.27  1.71    Male     No  Sun  Dinner     4
11       35.26  5.00  Female     No  Sun  Dinner     4

In [65]:
df.replace(2,method="ffill", limit=6, inplace=True)

C:\Users\KIIT\AppData\Local\Temp\ipykernel_22672\4266055429.py:1: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  df.replace(2,method="ffill", limit=6, inplace=True)

# interpolate()

In [3]:
df.interpolate()

C:\Users\KIIT\AppData\Local\Temp\ipykernel_38128\1671067507.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate()

    total_bill   tip     sex smoker  day    time  size
0        16.99  1.01  Female     No  Sun  Dinner     2
1        10.34  1.66    Male     No  Sun  Dinner     3
2        21.01  3.50    Male     No  Sun  Dinner     3
3        23.68  3.31    Male     No  Sun  Dinner     2
4        24.59  3.61  Female     No  Sun  Dinner     4
5        25.29  4.71    Male     No  Sun  Dinner     4
6         8.77  2.00    Male     No  Sun  Dinner     2
7        26.88  3.12    Male     No  Sun  Dinner     4
8        15.04  1.96    Male     No  Sun  Dinner     2
9        14.78  3.23    Male     No  Sun  Dinner     2
10       10.27  1.71    Male     No  Sun  Dinner     2
11       35.26  5.00  Female     No  Sun  Dinner     4

In [5]:
df.interpolate(method="linear")

C:\Users\KIIT\AppData\Local\Temp\ipykernel_38128\813095686.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(method="linear")

    total_bill   tip     sex smoker  day    time  size
0        16.99  1.01  Female     No  Sun  Dinner     2
1        10.34  1.66    Male     No  Sun  Dinner     3
2        21.01  3.50    Male     No  Sun  Dinner     3
3        23.68  3.31    Male     No  Sun  Dinner     2
4        24.59  3.61  Female     No  Sun  Dinner     4
5        25.29  4.71    Male     No  Sun  Dinner     4
6         8.77  2.00    Male     No  Sun  Dinner     2
7        26.88  3.12    Male     No  Sun  Dinner     4
8        15.04  1.96    Male     No  Sun  Dinner     2
9        14.78  3.23    Male     No  Sun  Dinner     2
10       10.27  1.71    Male     No  Sun  Dinner     2
11       35.26  5.00  Female     No  Sun  Dinner     4

In [7]:
df.interpolate(axis=0)

C:\Users\KIIT\AppData\Local\Temp\ipykernel_38128\2122669812.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(axis=0)

    total_bill   tip     sex smoker  day    time  size
0        16.99  1.01  Female     No  Sun  Dinner     2
1        10.34  1.66    Male     No  Sun  Dinner     3
2        21.01  3.50    Male     No  Sun  Dinner     3
3        23.68  3.31    Male     No  Sun  Dinner     2
4        24.59  3.61  Female     No  Sun  Dinner     4
5        25.29  4.71    Male     No  Sun  Dinner     4
6         8.77  2.00    Male     No  Sun  Dinner     2
7        26.88  3.12    Male     No  Sun  Dinner     4
8        15.04  1.96    Male     No  Sun  Dinner     2
9        14.78  3.23    Male     No  Sun  Dinner     2
10       10.27  1.71    Male     No  Sun  Dinner     2
11       35.26  5.00  Female     No  Sun  Dinner     4

In [9]:
df.interpolate(limit=2)

C:\Users\KIIT\AppData\Local\Temp\ipykernel_38128\805236748.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(limit=2)

    total_bill   tip     sex smoker  day    time  size
0        16.99  1.01  Female     No  Sun  Dinner     2
1        10.34  1.66    Male     No  Sun  Dinner     3
2        21.01  3.50    Male     No  Sun  Dinner     3
3        23.68  3.31    Male     No  Sun  Dinner     2
4        24.59  3.61  Female     No  Sun  Dinner     4
5        25.29  4.71    Male     No  Sun  Dinner     4
6         8.77  2.00    Male     No  Sun  Dinner     2
7        26.88  3.12    Male     No  Sun  Dinner     4
8        15.04  1.96    Male     No  Sun  Dinner     2
9        14.78  3.23    Male     No  Sun  Dinner     2
10       10.27  1.71    Male     No  Sun  Dinner     2
11       35.26  5.00  Female     No  Sun  Dinner     4

In [11]:
df.interpolate(limit_direction="forward")

C:\Users\KIIT\AppData\Local\Temp\ipykernel_38128\2215346824.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(limit_direction="forward")

    total_bill   tip     sex smoker  day    time  size
0        16.99  1.01  Female     No  Sun  Dinner     2
1        10.34  1.66    Male     No  Sun  Dinner     3
2        21.01  3.50    Male     No  Sun  Dinner     3
3        23.68  3.31    Male     No  Sun  Dinner     2
4        24.59  3.61  Female     No  Sun  Dinner     4
5        25.29  4.71    Male     No  Sun  Dinner     4
6         8.77  2.00    Male     No  Sun  Dinner     2
7        26.88  3.12    Male     No  Sun  Dinner     4
8        15.04  1.96    Male     No  Sun  Dinner     2
9        14.78  3.23    Male     No  Sun  Dinner     2
10       10.27  1.71    Male     No  Sun  Dinner     2
11       35.26  5.00  Female     No  Sun  Dinner     4

# MERGE

In [39]:
df1 = pd.DataFrame({"id": [1, 2, 3],"name": ["A", "B", "C"]})
df2 = pd.DataFrame({"id": [1, 2, 3],"salary": [20000, 30000, 40000]})
pd.merge(df1, df2, on="id")

   id name  salary
0   1    A   20000
1   2    B   30000
2   3    C   40000

In [21]:
pd.merge(df1, df2, on="id", how="outer", indicator=True)

   id name  salary _merge
0   1    A   20000   both
1   2    B   30000   both
2   3    C   40000   both

In [33]:
pd.merge(df1, df2, left_index=True, right_index=True, suffixes=("name", "python"))

   idname name  idpython  salary
0       1    A         1   20000
1       2    B         2   30000
2       3    C         3   40000

# CONCAT

In [35]:
sr1 = pd.Series([1,2,3,4])
sr2 = pd.Series([11,22,33,44])
pd.concat([sr1,sr2])

0     1
1     2
2     3
3     4
0    11
1    22
2    33
3    44
dtype: int64

In [43]:
pd.concat([df1,df2])

   id name   salary
0   1    A      NaN
1   2    B      NaN
2   3    C      NaN
0   1  NaN  20000.0
1   2  NaN  30000.0
2   3  NaN  40000.0

In [49]:
pd.concat([df1,df2], axis=1, join="inner")

   id name  id  salary
0   1    A   1   20000
1   2    B   2   30000
2   3    C   3   40000

In [51]:
pd.concat([df1, df2], keys=["DataFrame1", "DataFrame2"])

              id name   salary
DataFrame1 0   1    A      NaN
           1   2    B      NaN
           2   3    C      NaN
DataFrame2 0   1  NaN  20000.0
           1   2  NaN  30000.0
           2   3  NaN  40000.0

# GROUPBY

In [59]:
var = pd.DataFrame({"name":["a","b","c","d","a","b","a","b","c","c"],
                   "sub1":[12,13,14,12,13,14,15,23,25,16],
                   "sub2":[25,26,27,28,29,30,25,34,35,40]})
var

  name  sub1  sub2
0    a    12    25
1    b    13    26
2    c    14    27
3    d    12    28
4    a    13    29
5    b    14    30
6    a    15    25
7    b    23    34
8    c    25    35
9    c    16    40

In [61]:
gro = var.groupby("name")
gro

In [63]:
for x,y in gro:
    print(x)
    print(y)

a
  name  sub1  sub2
0    a    12    25
4    a    13    29
6    a    15    25
b
  name  sub1  sub2
1    b    13    26
5    b    14    30
7    b    23    34
c
  name  sub1  sub2
2    c    14    27
8    c    25    35
9    c    16    40
d
  name  sub1  sub2
3    d    12    28

In [65]:
gro.get_group("a")

  name  sub1  sub2
0    a    12    25
4    a    13    29
6    a    15    25

In [67]:
gro.min()

      sub1  sub2
name
a       12    25
b       13    26
c       14    27
d       12    28

In [69]:
gro.max()

      sub1  sub2
name
a       15    29
b       23    34
c       25    40
d       12    28

In [71]:
gro.mean()

           sub1       sub2
name
a     13.333333  26.333333
b     16.666667  30.000000
c     18.333333  34.000000
d     12.000000  28.000000

In [73]:
li = list(gro)
li

[('a',
    name  sub1  sub2
  0    a    12    25
  4    a    13    29
  6    a    15    25),
 ('b',
    name  sub1  sub2
  1    b    13    26
  5    b    14    30
  7    b    23    34),
 ('c',
    name  sub1  sub2
  2    c    14    27
  8    c    25    35
  9    c    16    40),
 ('d',
    name  sub1  sub2
  3    d    12    28)]

# JOIN

In [85]:
var1 = pd.DataFrame({"A":[12,13,14,11], "B":[15,16,17,18]}, index=[1, 2, 3,4])
var2 = pd.DataFrame({"C":[22,23,24,22], "D":[25,26,27,28]}, index=[1, 2, 3,4])
var1.join(var2)

    A   B   C   D
1  12  15  22  25
2  13  16  23  26
3  14  17  24  27
4  11  18  22  28

In [87]:
var1.join(var2, how="left")

    A   B   C   D
1  12  15  22  25
2  13  16  23  26
3  14  17  24  27
4  11  18  22  28

In [93]:
var1.join(var2, lsuffix="_left", rsuffix="_right")

    A   B   C   D
1  12  15  22  25
2  13  16  23  26
3  14  17  24  27
4  11  18  22  28

# APPEND

In [103]:
pd.concat([var1, var2], ignore_index=True)

      A     B     C     D
0  12.0  15.0   NaN   NaN
1  13.0  16.0   NaN   NaN
2  14.0  17.0   NaN   NaN
3  11.0  18.0   NaN   NaN
4   NaN   NaN  22.0  25.0
5   NaN   NaN  23.0  26.0
6   NaN   NaN  24.0  27.0
7   NaN   NaN  22.0  28.0

# MELT()

In [105]:
df = pd.DataFrame({"days": [1,2,3,4,5,6],"Math": [80, 90,36,86,74,85],"English": [70, 85,67,57,45,57]})
df

   days  Math  English
0     1    80       70
1     2    90       85
2     3    36       67
3     4    86       57
4     5    74       45
5     6    85       57

In [107]:
pd.melt(df)

   variable  value
0      days      1
1      days      2
2      days      3
3      days      4
4      days      5
5      days      6
6      Math     80
7      Math     90
8      Math     36
9      Math     86
10     Math     74
11     Math     85
12  English     70
13  English     85
14  English     67
15  English     57
16  English     45
17  English     57

In [115]:
pd.melt(df, id_vars=["days"], var_name="python", value_name="Sh")

    days   python  Sh
0      1     Math  80
1      2     Math  90
2      3     Math  36
3      4     Math  86
4      5     Math  74
5      6     Math  85
6      1  English  70
7      2  English  85
8      3  English  67
9      4  English  57
10     5  English  45
11     6  English  57

# PIVOT TABLE

In [129]:
df = pd.DataFrame({"Name": ["A", "A", "B", "B"],"Subject": ["Math", "English", "Math", "English"],"Marks": [80, 70, 90, 85]})
df

  Name  Subject  Marks
0    A     Math     80
1    A  English     70
2    B     Math     90
3    B  English     85

In [127]:
pd.pivot_table(df,values="Marks",index="Name",columns="Subject",aggfunc="mean")

Subject  English  Math
Name
A           70.0  80.0
B           85.0  90.0