In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\kiit\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\kiit\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\kiit\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\kiit\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\kiit\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\kiit\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

# SERIES

In [63]:
import pandas as pd
x = [3,4,5,6,7,8]
var = pd.Series(x, index=["a","b","c","d","e","f"], dtype="float", name="Python")
print(var)
print(type(var))
print(var[3])

a    3.0
b    4.0
c    5.0
d    6.0
e    7.0
f    8.0
Name: Python, dtype: float64
<class 'pandas.core.series.Series'>
6.0

C:\Users\KIIT\AppData\Local\Temp\ipykernel_39964\2289599830.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(var[3])

In [25]:
dic = {"name":["Python", "Java"], "Rank":[1,4]}
var1 = pd.Series(dic)
print(var1)

name    [Python, Java]
Rank            [1, 4]
dtype: object

In [31]:
s1 = pd.Series(12, index=[1,2,3,4,5,6])
s2 = pd.Series(12, index=[1,2,3,4])
print(s1+s2)

1    24.0
2    24.0
3    24.0
4    24.0
5     NaN
6     NaN
dtype: float64

# DATAFRAME

In [65]:
d={"a":[1,2,3,4], "b":[5,6,7,8]}
d1 = pd.DataFrame(d, columns=["a"], index=["a","b","c","d"])
print(type(d1))
print(d1)

<class 'pandas.core.frame.DataFrame'>
   a
a  1
b  2
c  3
d  4

In [47]:
import pandas as pd

s1 = pd.Series(["A", "B", "C"])
s2 = pd.Series([20, 21, 22])
s3 = pd.Series([85, 90, 78])

df = pd.DataFrame({"Name": s1,"Age": s2,"Marks": s3})

print(df)

  Name  Age  Marks
0    A   20     85
1    B   21     90
2    C   22     78

In [51]:
sr={"a":pd.Series(["A", "B", "C"]), "b":pd.Series([20, 21, 22])}
df = pd.DataFrame(sr)
print(df)

   a   b
0  A  20
1  B  21
2  C  22

# ARITHMETIC OPERATIONS

In [61]:
var = pd.DataFrame({"a":[1,2,3,4], "b":[5,6,7,8]})
var
var["c"] = var["a"]+var["b"]
print(var)

   a  b   c
0  1  5   6
1  2  6   8
2  3  7  10
3  4  8  12

# INSERT

In [73]:
var = pd.DataFrame({"A":[1,2,3,4], "B":[5,6,7,8]})
var

   A  B
0  1  5
1  2  6
2  3  7
3  4  8

In [75]:
var.insert(1, "C", var["A"])
var

   A  C  B
0  1  1  5
1  2  2  6
2  3  3  7
3  4  4  8

In [77]:
var.insert(1, "D", ["A","B","C","D"])
var

   A  D  C  B
0  1  A  1  5
1  2  B  2  6
2  3  C  3  7
3  4  D  4  8

In [81]:
var["E"] = var["A"][:3]
var

   A  D  C  B    E
0  1  A  1  5  1.0
1  2  B  2  6  2.0
2  3  C  3  7  3.0
3  4  D  4  8  NaN

# DELETE

In [103]:
var = pd.DataFrame({"A":[1,2,3,4], "B":[5,6,7,8], "C":[8,7,6,5], "D":[4,3,2,1]})
var

   A  B  C  D
0  1  5  8  4
1  2  6  7  3
2  3  7  6  2
3  4  8  5  1

In [105]:
var.pop("B")
var

   A  C  D
0  1  8  4
1  2  7  3
2  3  6  2
3  4  5  1

In [107]:
del var["A"]
var

   C  D
0  8  4
1  7  3
2  6  2
3  5  1

# WRITE THEN CREATE CSV FILE

In [109]:
dis = {"a":[1,2,3,4], "b":[5,6,7,8], "c":[4,6,3,7]}
d = pd.DataFrame(dis)
print(d)
d.to_csv("file_1.csv")

   a  b  c
0  1  5  4
1  2  6  6
2  3  7  3
3  4  8  7

In [111]:
dis = {"a":[1,2,3,4], "b":[5,6,7,8], "c":[4,6,3,7]}
d = pd.DataFrame(dis)
print(d)
d.to_csv("file_2.csv",index=False)

   a  b  c
0  1  5  4
1  2  6  6
2  3  7  3
3  4  8  7

In [113]:
dis = {"a":[1,2,3,4], "b":[5,6,7,8], "c":[4,6,3,7]}
d = pd.DataFrame(dis)
print(d)
d.to_csv("file_3.csv", index=False, header=["sh","at","ak"])

   a  b  c
0  1  5  4
1  2  6  6
2  3  7  3
3  4  8  7

# READ CSV FILE

In [123]:
df = pd.read_csv("C:\\Users\\KIIT\\Desktop\\Padho Likho\\tips.csv")
print(df)

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [135]:
df = pd.read_csv("C:\\Users\\KIIT\\Desktop\\Padho Likho\\tips.csv", nrows=5, usecols=["tip", "time"])
print(df)

    tip    time
0  1.01  Dinner
1  1.66  Dinner
2  3.50  Dinner
3  3.31  Dinner
4  3.61  Dinner

# PANDAS FUNCTION

In [171]:
df = pd.read_csv("C:\\Users\\KIIT\\Desktop\\Padho Likho\\tips.csv")
print(df)

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [139]:
df.index

RangeIndex(start=0, stop=244, step=1)

In [141]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [143]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [147]:
df.head(6)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4

In [149]:
df.tail(4)

     total_bill   tip     sex smoker   day    time  size
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [151]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [157]:
df[1:10:2]

   total_bill   tip   sex smoker  day    time  size
1       10.34  1.66  Male     No  Sun  Dinner     3
3       23.68  3.31  Male     No  Sun  Dinner     2
5       25.29  4.71  Male     No  Sun  Dinner     4
7       26.88  3.12  Male     No  Sun  Dinner     4
9       14.78  3.23  Male     No  Sun  Dinner     2

In [159]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [161]:
df.index.array

<NumpyExtensionArray>
[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
 ...
 234, 235, 236, 237, 238, 239, 240, 241, 242, 243]
Length: 244, dtype: int64

In [163]:
df.to_numpy()

array([[16.99, 1.01, 'Female', ..., 'Sun', 'Dinner', 2],
       [10.34, 1.66, 'Male', ..., 'Sun', 'Dinner', 3],
       [21.01, 3.5, 'Male', ..., 'Sun', 'Dinner', 3],
       ...,
       [22.67, 2.0, 'Male', ..., 'Sat', 'Dinner', 2],
       [17.82, 1.75, 'Male', ..., 'Sat', 'Dinner', 2],
       [18.78, 3.0, 'Female', ..., 'Thur', 'Dinner', 2]], dtype=object)

In [165]:
import numpy as np
v = np.asarray(df)
v

array([[16.99, 1.01, 'Female', ..., 'Sun', 'Dinner', 2],
       [10.34, 1.66, 'Male', ..., 'Sun', 'Dinner', 3],
       [21.01, 3.5, 'Male', ..., 'Sun', 'Dinner', 3],
       ...,
       [22.67, 2.0, 'Male', ..., 'Sat', 'Dinner', 2],
       [17.82, 1.75, 'Male', ..., 'Sat', 'Dinner', 2],
       [18.78, 3.0, 'Female', ..., 'Thur', 'Dinner', 2]], dtype=object)

In [167]:
df.sort_index(axis=0, ascending = False)

     total_bill   tip     sex smoker   day    time  size
243       18.78  3.00  Female     No  Thur  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
240       27.18  2.00  Female    Yes   Sat  Dinner     2
239       29.03  5.92    Male     No   Sat  Dinner     3
..          ...   ...     ...    ...   ...     ...   ...
4         24.59  3.61  Female     No   Sun  Dinner     4
3         23.68  3.31    Male     No   Sun  Dinner     2
2         21.01  3.50    Male     No   Sun  Dinner     3
1         10.34  1.66    Male     No   Sun  Dinner     3
0         16.99  1.01  Female     No   Sun  Dinner     2

[244 rows x 7 columns]

In [175]:
df.loc[0, "total_bill"]= "python"
df

C:\Users\KIIT\AppData\Local\Temp\ipykernel_39964\1574666829.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'python' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[0, "total_bill"]= "python"

    total_bill   tip     sex smoker   day    time  size
0       python  1.01  Female     No   Sun  Dinner     2
1        10.34  1.66    Male     No   Sun  Dinner     3
2        21.01  3.50    Male     No   Sun  Dinner     3
3        23.68  3.31    Male     No   Sun  Dinner     2
4        24.59  3.61  Female     No   Sun  Dinner     4
..         ...   ...     ...    ...   ...     ...   ...
239      29.03  5.92    Male     No   Sat  Dinner     3
240      27.18  2.00  Female    Yes   Sat  Dinner     2
241      22.67  2.00    Male    Yes   Sat  Dinner     2
242      17.82  1.75    Male     No   Sat  Dinner     2
243      18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [177]:
df.loc[[2,3],["total_bill","tip"]]

  total_bill   tip
2      21.01  3.50
3      23.68  3.31

In [179]:
df.iloc[0,1]

1.01

In [181]:
df.drop("tip", axis=1)

    total_bill     sex smoker   day    time  size
0       python  Female     No   Sun  Dinner     2
1        10.34    Male     No   Sun  Dinner     3
2        21.01    Male     No   Sun  Dinner     3
3        23.68    Male     No   Sun  Dinner     2
4        24.59  Female     No   Sun  Dinner     4
..         ...     ...    ...   ...     ...   ...
239      29.03    Male     No   Sat  Dinner     3
240      27.18  Female    Yes   Sat  Dinner     2
241      22.67    Male    Yes   Sat  Dinner     2
242      17.82    Male     No   Sat  Dinner     2
243      18.78  Female     No  Thur  Dinner     2

[244 rows x 6 columns]